name: CI/CD Pipeline (Experiment 10)

on:
  push:
    paths:
      - 'experiment10/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: experiment10

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-app .

    - name: Run Container
      run: docker run my-app